### ISSUE TITLE
Unable to re-send approval e-mail

### ISSUE THREAD

**Issue by webknjaz** [GDG-Ukraine/gdgregform#11]
First confirmation approval email is sent correctly. However if one tries to re-send it an error raises:

```
Re-sending email to

Are you sure you want to send invitation email to ?
The application is not accepted yet!
```

Re-login doesn't help.

**Comment by olostan** [comment]
So where is error? it is a warning to avoid occasional re-sending invitations.

**Comment by webknjaz** [comment]
error1 is 'The application is not accepted yet!', but it's accepted.
error2 is empty string instead of email.

**Comment by olostan** [comment]
Dublicates. See #12 and #13
