### ISSUE TITLE
UI bug during additional registration

### ISSUE THREAD

**Issue by zasadnyy** [GDG-Ukraine/gdgregform#19]
There is no need to show "Registration is closing soon" during additional registration.
Screenshot http://monosnap.com/image/MxPrQ5CP7W9Lu6T5lHB0v6sTa

**Comment by webknjaz** [comment]
wrong repo -> https://github.com/GDG-Ukraine/gdg.org.ua/issues
moreover. "Invites" feature isn't implemented in full
