### ISSUE TITLE
Error while access (admin rights)

### ISSUE THREAD

**Issue by ValeryP** [GDG-Ukraine/gdgregform#8]
I try get access web-interface to create registration form. When I go on this link http://olostan.org.ua:4242/admin/admin.html
I got error: Your account is not authorized to manage GDG data
@olostan can you fix this plz.
Thnx!

**Comment by webknjaz** [comment]
Did the app forward you to the google in order to ask for certain permissions?

**Comment by ValeryP** [comment]
No, only short text message.
![2013-05-10 14 46 31](https://f.cloud.github.com/assets/3534020/487777/57543a38-b967-11e2-90d0-63d799739ea6.png)

**Comment by webknjaz** [comment]
Please, try navigating to /auth URL manually. And also report your version of chrome/chromium? have you tried using other browsers?

**Comment by ValeryP** [comment]
1) I tried Opera 12.15 on Windows 7. 
2) The app forward me to google in order to ask for permissions. 
3) I accept it.
4) Then got the same error: Your account is not authorized to manage GDG data.

My chrome ver. is 27.0.1453.81 beta-m.
When I navigate to /auth URL manually in chrome, then I have the second step and the same result from 4-th step.

**Comment by webknjaz** [comment]
did you check that you use the same account you've provided us with?

**Comment by ValeryP** [comment]
Yes. Can we check this with your help again?

**Comment by webknjaz** [comment]
@olostan promised to get to his laptop this evening. He'll enable logging and will check what google actually provides to an app.

**Comment by ValeryP** [comment]
This will be great. Thnx you.

**Comment by webknjaz** [comment]
@ValeryP In seems some invisible symbol was copied to the DB. Please check now, I've retyped the email manually without copying.

**Comment by ValeryP** [comment]
Oh. Now all are OK. Thanks you.
